### PR TITLE
Updated node-inspector and other deps

### PR DESCRIPTION
**Pull request by fiznool**
I couldn't get the test to pass, but it wouldn't pass even before making these changes.

### CODE REVIEW

**Comment by ChrisWren** [comment]
Could you update the test string to make it pass and **not** bump the version number? I will bump package.json version when I release. Thanks for the PR!

**Comment by fiznool** [comment]
I couldn't get the test to pass at all, even using the code currently on master. So I don't really know what to do here.

**Comment by ChrisWren** [comment]
```
AssertionError: expected 'grunt-release\ngrunt-contrib-jshint\ngrunt-mdlint\ngrunt-simple-mocha\n\u001b[4mRunning "node-inspector:custom" (node-inspector) task\u001b[24m\nNode Inspector v0.10.0\nVisit http://localhost:1337/debug?ws=localhost:1337&port=5857 to start debugging.\n' to contain 'Visit http://localhost:1337/debug?port=5857 to start debugging.'
```

Looks like the output from node-inspector has changed and the assertion has to be updated.

**Comment by fiznool** [comment]
D'oh - of course. Sorry about that, should be fixed now.

**Comment by ChrisWren** [comment]
Thank you sir!

**Comment by fiznool** [comment]
Thanks for the speedy merge!

**Pull request merged**
